language: cpp

compiler:
  - gcc
  - clang

cache:
 apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tcl8.5-dev
      - tk8.5-dev
      - tclthread
      - libgl1-mesa-dri
      - xsltproc
      - libxi-dev

matrix:
  include:
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - libxi-dev
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - libxi-dev
  - os: linux
    compiler: gcc
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - libxi-dev
    dist: trusty
  - os: linux
    compiler: clang
    env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    dist: trusty
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - libxi-dev
  - os: linux
    compiler: gcc
  - os: linux
    compiler: gcc
    env: BUILD_USE_PCH=OFF
  - os: linux
    compiler: gcc
    env: USE_GL2PS=ON
    addons:
      apt:
        packages:
          - libgl2ps-dev
          - libxi-dev
  - os: linux
    compiler: gcc
    env: USE_FREEIMAGE=ON
    addons:
      apt:
        packages:
          - libfreeimage-dev
          - libxi-dev
  - os: linux
    compiler: gcc
    env: USE_TBB=ON
    addons:
      apt:
        packages:
          - libtbb-dev
          - libxi-dev
  - os: osx
    compiler: clang
  - os: osx
    compiler: clang
    env: BUILD_USE_PCH=OFF
  - os: osx
    osx_image: xcode8.3
    compiler: clang
  - os: osx
    osx_image: xcode9.2
    compiler: clang
  - os: osx
    osx_image: xcode9.3beta
    compiler: clang
  exclude:
  - env: RUN_TESTS=false BUILD_USE_PCH=ON 
  allow_failures:
    - os: osx

before_install:
  # osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install freetype;
        brew install freeimage;
        brew install gl2ps;
    fi
  # linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        eval "${MATRIX_EVAL}";
    fi

before_script:
#  Initialize xvfb server
#  Depth is necessary, otherwise DRAWEXE exits with this message:
#    Tcl Exception: ** Exception ** 0x7fee03adb307 : Aspect_WindowDefinitionError: Xw_Window, couldn't find compatible Visual (RGBA, double-buffered)
#  Remove OCCT tests which are going to be skipped
#  because of missing data files.  We must use -name
#  to filter out 'begin' or 'end' files.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16";
        find tests -type f -name '[A-Z][0-9]' -o -name 'Z[A-Z][0-9]' -o -name 'bu[gc]*' | xargs grep -l locate_data_file /dev/null | xargs rm -f;
        rm -rf tests/chamfer tests/de tests/mesh tests/perf/*_mesh_*;
    fi
  - mkdir cmake-build
  - cd cmake-build

script: sh ../.travis.build.sh

after_script:
  - test ! -r occt/summary.xml || xsltproc --param duration 1 ../.travis.xsl occt/summary.xml
  - if [ -r occt/summary.xml ]; then
        xsltproc ../.travis.xsl occt/summary.xml > occt/summary.failed;
        if [ -s occt/summary.failed ]; then
            echo "FAILED TESTS:";
            cat occt/summary.failed;
            for file in $(cat occt/summary.failed); do head -n -1 occt/$file.{tcl,log}; done;
        fi;
    fi

branches:
  only:
    - master
    - /^review/
