language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libxmu-dev tcl8.5-dev tk8.5-dev libgl2ps-dev
#  Needed to run OCCT tests in parallel
  - sudo apt-get install tclthread
#  Is this needed to run OCCT tests?
  - sudo apt-get install libgl1-mesa-dri
before_script:
#  Remove OCCT tests which are going to be skipped
#  because of missing data files.  We must use -name
#  to filter out 'begin' or 'end' files.
  - find tests -type f -name '[A-Z][0-9]' -o -name 'Z[A-Z][0-9]' -o -name 'bu[gc]*' | xargs grep -l locate_data_file /dev/null | xargs rm -f
  - rm -rf tests/chamfer tests/de tests/mesh tests/perf/*_mesh_*
#  Builds hang, remove some tests to find the culprit
#  GOOD: - rm -rf tests/bugs tests/demo tests/xml
#  BAD - rm -rf tests/bugs tests/demo
#  BAD - rm -rf tests/xml/xcaf_*
  - rm -rf tests/xml/ocaf_*
  - mkdir cmake-build
  - cd cmake-build
#  Depth is necessary, otherwise DRAWEXE exits with this message:
#    Tcl Exception: ** Exception ** 0x7fee03adb307 : Aspect_WindowDefinitionError: Xw_Window, couldn't find compatible Visual (RGBA, double-buffered)
script: xvfb-run -s "-screen 0 1024x768x16" ../.travis.build.sh
after_script:
  - cat occt/summary.xml || true
branches:
  only:
    - master
    - /^review/

