version: oce-0.19.{build}

environment:
  oce_version: 0.19
  matrix:
    - generator: "MinGW Makefiles"
      ARCH: "i686"
      Compiler: MinGW-gcc-5.3.0
      BINDIR: C:\MinGW\bin
    - generator: "MinGW Makefiles"
      ARCH: "Win64"
      Compiler: MinGW64-gcc-6.3.0
      BINDIR: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    - generator: "MinGW Makefiles"
      ARCH: "Win64"
      Compiler: MinGW64-gcc-7.2.0
      BINDIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
    - generator: "Visual Studio 12"
      ARCH: "Win32"
      Compiler: "MSVC2013"
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2013"
    - generator: "Visual Studio 14"
      ARCH: "Win32"
      Compiler: "MSVC2015"
    - generator: "Visual Studio 14 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2015"

configuration:
  - Release

branches:
  only:
    - master
    - /^review/

shallow_clone: true 

# scripts that are called at very beginning, before repo cloning
init:

before_build:

# scripts that run after cloning repository
install:
  - cmd: CALL FetchBundle.bat

build_script:
  - if "%generator%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%BINDIR%"=="" (set "PATH=%PATH%;%BINDIR%")
  - if "%generator%" == "MinGW Makefiles" (CALL C:\projects\oce\appveyor-scripts\make-oce-msys.bat)
      else (CALL C:\projects\oce\appveyor-scripts\make-oce-msvc.bat)

after_build:
  - cmd: 7z a oce-%oce_version%.%ARCH%.%Compiler%.zip C:\oce-%oce_version% > nul
  - cmd: dir oce-%oce_version%.%ARCH%.%Compiler%.zip

artifacts:
  - path: oce-%oce_version%.%ARCH%.%Compiler%.zip

test: off  # to avoid discovering tests
